config/routes.rb
Rails.application.routes.draw do


  resources :houses
  root 'home#index'
  resources :real_estate_companies


  devise_scope :hunter do
    root :to => "hunters/sessions#new"
  end

  devise_for :hunters, controllers: {
      sessions: 'hunters/sessions',
      registrations: 'hunters/registrations'
  }
  resources :hunters, only: [:index]
  get  '/hunterindex',  to: 'hunters#index'
  resources :hunters, path: 'admins/manage/hunters',
            controller: 'admins/manage_hunters',
            as: :hunter




  devise_scope :admin do
    root :to => "admins/sessions#new"
  end

  devise_for :admins, controllers: {
      sessions: 'admins/sessions',
      registrations: 'admins/registrations'
  }
  resources :admins, only: [:index]
  get  '/adminindex',  to: 'admins#index'




  devise_scope :realtor do
    root :to => "realtors/sessions#new"
  end

  devise_for :realtors, controllers: {
      sessions: 'realtors/sessions',
      registrations: 'realtors/registrations'
  }
  resources :realtors, only: [:index]
  get  '/realtorindex',  to: 'realtors#index'
  resources :realtors, path: 'admins/manage/realtors',
            controller: 'admins/manage_realtors',
            as: :realtor

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Welcome to REM APP</h1>


<%= link_to 'Login admin!', new_admin_session_path, :class => "nav-link" %></br>
<%= link_to 'Login realtors!', new_realtor_session_path, :class => "nav-link" %>
<%= link_to 'Signup realtors!', new_realtor_registration_path, :class => "nav-link" %></br>
<%= link_to 'Login hunters!', new_hunter_session_path, :class => "nav-link" %>
<%= link_to 'Signup hunters!', new_hunter_registration_path, :class => "nav-link" %>