config/routes.rb
Rails.application.routes.draw do


  resources :houses
  root 'home#index'
  resources :real_estate_companies


  devise_scope :hunter do
    root :to => "hunters/sessions#new"
  end

  devise_for :hunters, controllers: {
      sessions: 'hunters/sessions',
      registrations: 'hunters/registrations'
  }
  resources :hunters, only: [:index]
  get  '/hunterindex',  to: 'hunters#index'
  resources :hunters, path: 'admins/manage/hunters',
            controller: 'admins/manage_hunters',
            as: :hunter




  devise_scope :admin do
    root :to => "admins/sessions#new"
  end

  devise_for :admins, controllers: {
      sessions: 'admins/sessions',
      registrations: 'admins/registrations'
  }
  resources :admins, only: [:index]
  get  '/adminindex',  to: 'admins#index'




  devise_scope :realtor do
    root :to => "realtors/sessions#new"
  end

  devise_for :realtors, controllers: {
      sessions: 'realtors/sessions',
      registrations: 'realtors/registrations'
  }
  resources :realtors, only: [:index]
  get  '/realtorindex',  to: 'realtors#index'
  resources :realtors, path: 'admins/manage/realtors',
            controller: 'admins/manage_realtors',
            as: :realtor

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admins/manage_hunters_controller.rb
# frozen_string_literal: true

# Controller to manage hunters
class Admins::ManageHuntersController < ApplicationController
  include ApplicationHelper

  before_action :authenticate!

  def index
    @hunters = Hunter.all
  end

  def show
    redirect_to '/admins/manage/hunters'
  end

  def new
    @hunter = Hunter.new
  end

  def create
    @hunter = Hunter.new(allowed_params)

    if @hunter.save
     redirect_to '/admins/manage/hunters', flash: {
          notice: 'Successfully Created!',
          class: 'alert alert-success'
      }
    end
  end

  def edit
    @hunter = Hunter.find(params[:id])
  end

  def update
    @hunter = Hunter.find(params[:id])
    if @hunter.update_attributes(allowed_params)
      redirect_to '/admins/manage/hunters', flash: {
        notice: 'Successfully Updated!',
        class: 'alert alert-success'
      }
    else
      render action: 'edit'
    end
  end

  def destroy
    @hunter = Hunter.find(params[:id])
    notice = { class: 'alert alert-success', notice: 'Successfully Deleted!' }
    unless @hunter.destroy
      notice[:class] = 'alert alert-danger'
      notice[:notice] = @hunter.errors.full_messages
      notice[:notice] = notice[:notice].map { |m| "<span>#{m}</span>" }
      notice[:notice] = notice[:notice].join('<br>')
    end
    redirect_to '/admins/manage/hunters', flash: notice
  end

  protected

  def authenticate!
    return if admin_signed_in?

    redirect_to :root, flash: UNAUTHORIZED_FLASH
  end

  def configure_permitted_parameters
    params.require(:hunter)
        .permit(:name, :phone, :prefcon, :email, :password, :password_confirmation)
  end
  def allowed_params
    params.require(:hunter)
          .permit(:name, :phone, :prefcon, :email, :password, :password_confirmation)
  end
end

app/views/admins/manage_hunters/edit.html.erb
<div class="container">
    <%= form_for @hunter, url: hunter_path(@hunter), method: :put do |f| %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :phone %><br />
      <%= f.text_field :phone, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :preferred_contact %><br />
      <%= f.select :prefcon, [ 'Phone', 'Email'], :prompt => 'Select One' %>
    </div>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

        <div class="form-group">
            <%= f.submit "Submit", :class => "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/admins/manage_hunters/index.html.erb
<div class="container">
    <table class="table table-hover table-striped table-bordered">
        <caption>List of House Hunters</caption>
        <thead class="thead-dark">
            <tr>
                <th class="header">Name</th>
                <th class="header">Email</th>
                <th class="header">Phone Number</th>
                <th class="header">Preferred Contact</th>
                <th class="header" colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @hunters.each do |u| %>
                <tr>
                    <td><%= u.name %></td>

                    <td>
                        <a href="mailto:<%= u.email %>" target="_blank"><%= u.email %></a>
                    </td>
                    <td>
                        <a href="call:<%= u.phone %>" target="_blank"><%= u.phone %></a>
                    </td>
                    <td>
                        <%= u.prefcon == 0 ? "Email" : "Phone" %>
                    </td>
                    <td>
                        <%= link_to "Edit", edit_hunter_path(u), :class => "btn btn-success" %>
                    </td>
                    <td>
                        <%= button_to "Delete", hunter_path(u),
                            method: :delete,
                            data: { confirm: "Are you sure?" },
                            :class => "btn btn-danger" %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <%= button_to "Create", new_hunter_path, method: :get, :class => "btn btn-primary" %>
</div>

app/views/admins/manage_hunters/new.html.erb
<div class="container">
    <%= form_for @hunter, url: hunter_index_path, method: :post do |f| %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :phone %><br />
      <%= f.text_field :phone, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :preferred_contact %><br />
      <%= f.select :prefcon, [ 'Phone', 'Email'], :prompt => 'Select One' %>
    </div>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

        <div class="form-group">
            <%= f.submit "Submit", :class => "btn btn-primary" %>
        </div>
    <% end %>
</div>